name: Windows C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: gcc Project_main.c -o Project_main.exe
    - name: run
      run: .\Project_main.exe
